version: "3.8"
services:
  postgres:
    container_name: salesflow_postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: salesflow_crm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
